source 'https://rubygems.org'
ruby '2.5.1'

#gem 'nokogiri'
#gem 'rspec'
#gem 'colorize'
#gem 'pry'
#gem 'rubocop', '~> 0.57.2'
#gem 'open-uri'
#gem 'csv'
#gem 'watir'
#gem 'dotenv'
gem 'sinatra'
gem 'shotgun'